kind: BuildConfig
apiVersion: v1
metadata:
  annotations:
    description: Build a container and push it to image streams
  labels:
    app: wordpress
  name: dn-story-job-container-2
  namespace: dn-story-test
spec:
  output:
    to:
      kind: DockerImage
      name: 'docker-registry.default.svc:5000/dn-story-test/job-container'
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: git@github.com:thanhbui1133/s2i-wordpress.git
    sourceSecret:
      name: deploy-git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: 'openshift/command/Dockerfile'
  triggers: []