---
kind: Template
apiVersion: v1
metadata:
  name: import-media-folder-from-s3
  annotations:
    openshift.io/display-name: "Import WP Media from S3"
    description: Application (a scheduled job that runs only once) for restoring or importing WP media files (folder "uploads") from S3
    tags: file,s3aws,wordpress
message: |-
  The following service(s) have been created in your project: ${NAME}.
labels:
  template: import-media-folder-from-s3
  app: "wordpress"
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: "${NAME}-secret"
    labels:
      app: "wordpress-${NAME}"
  stringData:
    aws-access-key-id: "${AWS_ACCESS_KEY_ID}"
    aws-secret-access-key: "${AWS_SECRET_ACCESS_KEY}"
- kind: Job
  apiVersion: batch/v1
  metadata:
    name: "${NAME}"
    labels:
      app: "wordpress-${NAME}"
  spec:
    template:
      metadata:
        name: "${NAME}"
      spec:
        containers:
        - name: wordpress
          image: thanhbui1133/backup_restore_s3_openshift
          imagePullPolicy: Always
          command: ["/var/lib/mysql/bin/import_wp_uploads_from_s3.sh"]
          volumeMounts:
          - mountPath: "${MOUNT_PATH}"
            name: "${NAME}-data"
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: "${NAME}-secret"
                key: aws-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: "${NAME}-secret"
                key: aws-secret-access-key
          - name: AWS_BUCKET_PATH
            value: "${AWS_BUCKET}"
        volumes:
        - name: "${NAME}-data"
          persistentVolumeClaim:
            claimName: "${STORAGE_PVC_WP}"
        restartPolicy: OnFailure
parameters:
- name: NAME
  displayName: Name of job
  required: true
- name: AWS_ACCESS_KEY_ID
  displayName: Amazon WebService Access Key ID
  required: true
- name: AWS_SECRET_ACCESS_KEY
  displayName: Amazon WebService Secret Key
  required: true
- name: AWS_BUCKET
  displayName: Amazon Bucket file path
  required: true
  value: s3://example/EX_dd_mm_yy/uploads
- name: STORAGE_PVC_WP
  displayName: Persistent Volume Claim Name
  description: The Pesistent Volumne Claim where Wordpress "wp-content" files locate
  required: true
- name: MOUNT_PATH
  displayName: Mount Path
  description: The mount path of container.
  required: true
  value: /opt/app-root/wp-content