kind: BuildConfig
apiVersion: v1
metadata:
  annotations:
    description: Build a container and push it to image streams
  labels:
    app: wordpress-tungtest
  name: bn-bonniernews-tungtest-container
  namespace: bn-bonniernews-test
spec:
  output:
    to:
      kind: DockerImage
      name: 'docker-registry.default.svc:5000/bn-bonniernews-test/wordpress:4.9.8-php-7.0'
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: git@github.com:BonnierNews/s2i-wordpress.git
    sourceSecret:
      name: deploy-git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: 'Dockerfile.7.0'
      buildArgs:
        - name: 'WORDPRESS_VERSION'
          value: '4.9.8'
  triggers: []